language: node_js
cache: yarn
node_js:
  - "8"
script: npm run test
before_install: npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
  # Send coverage data to coveralls.
  - npm run test:cover
