language: node_js
cache: yarn
node_js:
  - "8"
script: yarn run test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
  # Send coverage data to coveralls.
  - yarn run test:cover
